org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment
mc_version=1.20.1
mc_version_range=[1.20.1]
forge_version=47.3.0
forge_version_range=[47.1.0,)
loader_version_range=[47,)
mappings_channel=parchment
mappings_version=2023.09.03-1.20.1
pack_format_number=15

# Mod
mod_id=compatoplenty
mod_group=com.seleneandmana.compatoplenty
mod_name=Compat O' Plenty
mod_version=1.20.1-1.0.0
mod_license=Apache-2.0
mod_url=https://modrinth.com/mod/compat-o-plenty
mod_github=https://github.com/KreloX/compat-o-plenty
mod_credits=Selene and Mana
mod_authors=KreloX
mod_description=A mod designed to fill the gap in content between Biomes O' Plenty and other major mods.

# Dependencies
emi_version=1.1.20+1.20.1+forge
biomes_o_plenty_version=19.0.0.94
glitchcore_version=0.0.1.1
terrablender_version=1.20.1-3.0.1.10
blueprint_version=1.20.1-7.1.0
every_compat_version=1.20-2.7.21
moonlight_version=forge_1.20-2.13.73
boatload_version=1.20.1-5.0.1
woodworks_version=3.0.2
clayworks_version=3.0.3
quark_version=1.20.1-4.0-460
zeta_version=1.20.1-1.0-24
farmers_delight_version=1.20.1-1.2.7
twigs_version=1.20.1-3.1.1